// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Nuova_cartella.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Purchase", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PrezzoTotale")
                        .HasColumnType("REAL");

                    b.Property<double>("prezzo")
                        .HasColumnType("REAL");

                    b.Property<string>("prodotto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("Registrazione", b =>
                {
                    b.Property<int>("RegistrazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("cognome")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ruolo")
                        .HasColumnType("TEXT");

                    b.Property<string>("sesso")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrazioneId");

                    b.ToTable("Registrazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
